spring.application.name=Arogeva

server.port=8082





#spring.datasource.url=jdbc:postgresql://192.168.10.25:5432/ArogevaDb
spring.datasource.url=jdbc:postgresql://localhost:5432/arogeva_db
#spring.datasource.url=jdbc:postgresql://192.168.10.25:5432/ArogevaDb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.session.store-type=none

# SpringDoc OpenAPI Configuration
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.url=/v3/api-docs
#springdoc.swagger-ui.urls[0].name=Local API
#springdoc.swagger-ui.urls[0].url=/v3/api-docs
#springdoc.swagger-ui.operations-sorter=method
#springdoc.swagger-ui.tags-sorter=alpha
#springdoc.show-actuator=false
#springdoc.swagger-ui.use-root-path=true

